# action.yaml
name: 'Anchor Results To Job Summary'
description: 'A GitHub Action that converts Anchor container scan results to a github job summary'
inputs:
  results_file:
    description: 'The Anchor results file name and path'
    required: true
    default: "results.json"
  severity_threshold:
    description: 'The severitiy threshold you want to include in your report'
    required: true
    default: "medium"
runs:
  using: 'docker'
  image: "Dockerfile"
